rate:
  - totally
  - absolutely
  - really

star:
  1:
    - the worst ever
    - a stinky hole
    - really old grabage
    - a disaster
  2:
    - shit
    - a hole
    - grabage
  3:
    - ok
    - tolerable
    - mediocre
  4:
    - good
    - normal
    - decent
  5:
    - awesome
    - unforgattable
    - brilliant
    - like heaven
    - perfect

Bar:
  0:
    title:
      - bartenders
      - waitresses
    verb:
      - are
    grades:
      5:
        - really talanted, and sometimes they forget to charge me
        - absolutely good loking. I was drinking my liquor and happily staring at them
      4:
        - handsome and they did their job pretty good, but I wish they were a bit prettier
        - really good, but a bit slow at puring whiskey to my glass
      3:
        - mediocre looking and arn't trying too hard to make me wasted
        - doing well, hovewer they are a bit creepy and try to get my number
      2:
        - bad looking and smell bad. One didn't give me his number and totally ignored me after. I hate that person for that.
        - always wasted and dont't really work. Last time I was there, they were just having sex and ignored my orders. They were just saying someting like "it's already 2am we are flosed" but I was too drunk to listen to their shit.
      1:
        - total jerks. One chased me to my door trying to get some money from me. Dont remember details thought, I was pretty drunk that night.
        - assholes. Total assholes. They tried to spank me with their whip and put roofy into my eleventh shot of vodka.
  1:
    title: 
      - beer
      - whiskey
      - whine
    verb:
      - is      
    grades:
      5:
        - delicious like a young and naive virgin
        - perfect like google search. Not like yahoo search.
      4:
        - pretty good, but not very cheap, which is important to me
        - pretty cheap, but not so tasty, but screw the taste, getting wasted is more important.
      3:
        - drinkable, but a little warm. Good there were some girls too, otherwise I'd give this place 2 stars.
        - not bad, but expensive like hell. I had to bring my own flask and drink it while my date in the bathroom.
      2:
        - terrible. It made me feel bad, even after 11th glass. I had to go to the bathroom and throw up. Good it was cheap enough.
        - like somebody's pee. The taste and the color. Only good thing is that the bartender is handsome.
      1:
        - the worst in my life. Not only I spent 2 hours in the bathroom after, the waiter stole my wallet and used my credit card to buy porn that I don't even like.
        - just like machine oil. Tasted terrible, made me want to get wasted. Probably they mixed it with some dog pee so it tastes better than machine oil.

recommendations:
  5:
    - You have to go and check out that place, especially if you like booze. I recommend you drinking as many cocktails as you can, nerdy face.
    - You MUST go there and get wasted. Bring your date or your every date. The chances you get laid in that bar are very high.
  4:
    - If you don't mind expensive beer you MUST check that place. Or just bring your own alcohol and drink it in the bathroom.
    - A good place. I recommend, kinda. You can come, especially if you don't have any other options. Maybe you'll find a date.
  3:
    - It's a place to go if you don't have any other options. If you don't mind Marina-like bars. Douchebaggy, but you still can get wasted.
    - You can go there. Booze is drinkable. It's fine, you won't be very upset. Just try not to argue with the bartender, he's got a hammer.
  2:
    - I do recomment to go to any other bar but not this bar. Screw this place
    - I recommend to avoid this place and forget this place and remove it from google maps and yelp.
  1: 
    - I recommend you going to this place ONLY if you total douchebag. Screw this place, its the worst place ever. I recommend yelp to delete this place from it's database and to kick this bartender.
    - I recommend to come to this place just so you can kick the bartender and yell at people there that they all are assholes. Screw that place. Just bring tomatoes and throw them into windows.